### PR TITLE
Enable cross origin resource sharing.

### PR DESCRIPTION
**Pull request by garrickb**
This will allow the web app and xamarin app to make API requests.

### CODE REVIEW

**Comment by jackhorton** [comment]
https://github.com/expressjs/cors ???

**Comment by garrickb** [comment]
uhh, didn't know that was a thing; this works just as well :smile:

**Comment by jackhorton** [comment]
Id prefer if we used the standard...

**Comment by jackhorton** [comment]
Good work, soldier

**Pull request merged**
